### ISSUE TITLE
Fix CI to work with PHP 7.4 and 8.x

### ISSUE THREAD

**Issue by SOHELAHMED7** [php-openapi/yii2-fractal#4]
https://github.com/php-openapi/yii2-fractal/actions/runs/9379632474

**Comment by SOHELAHMED7** [comment]
@cebe 

I think we have to drop support for PHP 7.4 because in order to fix https://github.com/php-openapi/yii2-fractal/actions/runs/9379632474/job/25824965317 we need codeception/module-phpbrowser to at least 2.0.3

That requires codeception/lib-innerbrowser to 2.*

While achieving the above, Composer complains that codeception/module-yii2 requires codeception/lib-innerbrowser 1.* for PHP 7.4

There is [no version](https://github.com/Codeception/module-yii2/releases) of codeception/module-yii2 which supports PHP 7.4 and is dependent on codeception/lib-innerbrowser 1.*

v1.1.5 of codeception/module-yii2 requires codeception/lib-innerbrowser 1.*

v1.1.6 of codeception/module-yii2 requires codeception/lib-innerbrowser 2.* and PHP ^8

What are your thoughts?

**Comment by cebe** [comment]
I'm okay with going to >=8.0 only for this library.
